.TH DITCH 1 "25 November 2020"
.SH NAME
ditch \- display menu of twitch streamers currently online
.SH SYNOPSIS
.B ditch
.RB [ \-f ]
.SH DESCRIPTION
.B ditch
is a filter that reads a list of twitch login names from standard input.  It
converts these login names into a list of respective users who are currently
live and presents a menu using
.BR bemenu (1).
Selections are then provided to
.BR mpv (1)
for streaming with functionality provided by
.BR youtube-dl (1).
.SH OPTIONS
.TP
.B -f
Force
.B ditch
to generate a new list instead of reusing the cache.
.SH EXIT STATUS
.B ditch
usually returns
.B zero
even if the provided twitch login does not exist.  Instead only valid login
names are printed.
.P
Any
.B non-zero
exit status will come from whichever command failed during the execution of
.BR ditch .
.SH NOTES
.B ditch
does not use
.B bemenu
directly but executes a command called
.B menu
with additional flags specific to
.BR bemenu .
This is done so common flags can be defined in
.B menu
for all invocations of
.B bemenu
across multiple scripts.
.SH EXAMPLE
.nf
printf draqu_ | ditch
.fi
.nf
ditch < ~/.local/share/ditch/streamers
.fi
.SH SOURCE
.UR https://github.com/Earnestly/dotfiles/blob/master/.local/bin/ditch
.UE
.SH SEE ALSO
.BR mpv (1),
.BR youtube-dl (1),
.BR bemenu (1)
