" XDG_CONFIG_HOME/vim/vimrc

" XXX Still necessary?
"     In 2026? Yes.
let &undodir = $MYVIMDIR . 'undo' | call mkdir(&undodir, 'p')
let &directory = $MYVIMDIR . 'swap' | call mkdir(&directory, 'p')
let &backupdir = $MYVIMDIR . 'backup' | call mkdir(&backupdir, 'p')
let &viminfofile = $MYVIMDIR . 'viminfo'

" Replace ex-mode with vim's command-line window.
map Q q:

syntax on
filetype indent plugin on

" XXX Without patching vim there is no way to remove the condescending delay
"     on initial edits in readonly buffers. Instead the readonly option is
"     simply removed to workaround this limitation.
"     https://github.com/vim/vim/issues/472
autocmd BufReadPost * setlocal noreadonly

set title
set number
set hidden
set backup
set showcmd
set ttyfast
set autoread
set undofile
set wildmenu
set linebreak
set smartcase
set ignorecase
set lazyredraw
set nomodeline
set nohlsearch
set nostartofline
set relativenumber
set scrolloff=1
set numberwidth=1
set colorcolumn=81
set cinoptions+=t0
set ttimeoutlen=50
set backspace=indent,eol,start

set list
set listchars=tab:\ \ ,trail:~

set cursorline
set laststatus=2
set statusline=%n\ %F\ %M%=%y%w%r%h\ %{&fenc}\ %l,%c\ %p%%\ %L

set expandtab
set tabstop=4
set shiftwidth=4

if !empty($DISPLAY)
    " Use the Xorg's primary selection as default register.
    set clipboard=unnamed
endif

if &t_Co >= 256 && (&term == 'xterm-256color' || &term == 'tmux-256color')
    " XXX This causes the :terminal feature to use libvterm's standard
    "     palette. See g:terminal_ansi_colors to set them.
    set termguicolors

    " These are only set if TERM is equal to xterm.  See :help xterm-true-color
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

    set background=dark

    colorscheme base16-yesterdaynight

    " By default my theme highlights the matching parenthesis with a
    " lighter colour while darkening the cursor causing me endless
    " confusion.  Using standout reverses the effect.
    hi MatchParen gui=standout
endif

" Use bsdtar for all the additional formats it supports over GNU tar.
let g:tar_cmd = 'bsdtar'
let g:tar_secure = 1

" Tell vim about the additional filetypes supported by bsdtar.
autocmd BufReadCmd *.iso,*.rar,*.7z call tar#Browse(expand("<amatch>"))

runtime! macros/matchit.vim

function! MinpacInit() abort
    try
        packadd minpac

    catch /^Vim(packadd):E919:/
        call systemlist(['git', 'clone', 'https://github.com/k-takata/minpac.git', $MYVIMDIR . 'pack/minpac/opt/minpac'])

        packadd minpac
    endtry

    call minpac#init()
    call minpac#add('k-takata/minpac', {'type': 'opt'})

    call minpac#add('dense-analysis/ale')
    call minpac#add('oils-for-unix/oils.vim')
    call minpac#add('kaarmu/typst.vim')
    call minpac#add('vim-erlang/vim-erlang-runtime')
    call minpac#add('ledger/vim-ledger')
    call minpac#add('tpope/vim-repeat')
    call minpac#add('tpope/vim-surround')
    call minpac#add('ziglang/zig.vim')

    silent! helptags ALL
endfunc

command! MinpacUpdate call MinpacInit() | call minpac#update()
command! MinpacClean  call MinpacInit() | call minpac#clean()

function SetPluginSettings()
    if get(g:, 'loaded_ledger')
        " https://github.com/ledger/vim-ledger/issues/143
        let g:ledger_is_hledger=v:false
    endif

    if get(g:, 'loaded_ale')
        " Remove the line noise.
        let g:ale_virtualtext_cursor = 'disabled'

        " Ideally only tigger on document save.
        let g:ale_lint_on_save = 1
        let g:ale_lint_on_enter = 0
        let g:ale_lint_on_text_changed = 0
        let g:ale_lint_on_insert_leave = 0
        let g:ale_lint_on_filetype_changed = 0

        if &t_Co >= 256 && (&term == 'xterm-256color' || &term == 'tmux-256color')
            " XXX There must be a better way than this to inherit a highlight
            "     group when making adjustments to it.
            call hlset([hlget('LineNr', v:true)[0]->extend(#{name: 'ALEErrorSign', guifg: string(hlget('Error')[0].guibg)})])
            call hlset([hlget('LineNr', v:true)[0]->extend(#{name: 'ALEWarningSign', guifg: string(hlget('Todo')[0].guifg)})])
            call hlset([hlget('LineNr', v:true)[0]->extend(#{name: 'ALEInfoSign', guifg: string(hlget('Function')[0].guifg)})])
        endif

        let g:ale_sign_error = '▐'
        let g:ale_sign_style_error = '▐'
        let g:ale_sign_warning = '▐'
        let g:ale_sign_style_warning = '▐'
        let g:ale_sign_info = '▐'
    endif
endfunc

autocmd VimEnter * call SetPluginSettings()
