" XDG_CONFIG_HOME/vim/vimrc

" XXX Still necessary?
let vimdir = fnamemodify($MYVIMRC, ':h')
let &undodir = vimdir . '/undo' | call mkdir(&undodir, 'p')
let &directory = vimdir . '/swap' | call mkdir(&directory, 'p')
let &backupdir = vimdir . '/backup' | call mkdir(&backupdir, 'p')
let &viminfofile = vimdir . '/viminfo'
unlet vimdir

" Replace ex-mode with vim's command-line window.
map Q q:

syntax on
filetype indent plugin on

set title
set number
set hidden
set backup
set showcmd
set ttyfast
set autoread
set undofile
set wildmenu
set linebreak
set smartcase
set ignorecase
set lazyredraw
set nomodeline
set nohlsearch
set nostartofline
set scrolloff=1
set numberwidth=1
set colorcolumn=81
set cinoptions+=t0
set ttimeoutlen=50
set backspace=indent,eol,start

set list
set listchars=tab:\ \ ,trail:~

set cursorline
set laststatus=2
set statusline=%n\ %F\ %M%=%y%w%r%h\ %{&fenc}\ %l,%c\ %p%%\ %L

set expandtab
set tabstop=4
set shiftwidth=4

if !empty($DISPLAY)
    " Use the Xorg's primary buffer as default register.
    set clipboard=unnamed
endif

if &t_Co >= 256 && (&term == 'xterm-256color' || &term == 'tmux-256color')
    " XXX This causes the :terminal feature to use libvterm's standard
    "     palette. See g:terminal_ansi_colors to set them.
    set termguicolors

    " These are only set if TERM is equal to xterm.  See :help xterm-true-color
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

    set background=dark

    colorscheme base16-yesterdaynight

    " By default my theme highlights the matching parenthesis with a
    " lighter colour while darkening the cursor causing me endless
    " confusion.  Using standout reverses the effect.
    hi MatchParen gui=standout
endif

" Use bsdtar for all the additional formats it supports over GNU tar.
let g:tar_cmd = 'bsdtar'
let g:tar_secure = 1

" Tell vim about additional formats.
autocmd BufReadCmd *.iso,*.rar,*.7z call tar#Browse(expand("<amatch>"))

runtime! macros/matchit.vim

function SetPluginSettings()
    if get(g:, 'loaded_ledger')
        " https://github.com/ledger/vim-ledger/issues/143
        let g:ledger_is_hledger=v:false
    endif

    if get(g:, 'loaded_ale')
        " Ideally only tigger on document save.
        let g:ale_lint_on_save = 1
        let g:ale_lint_on_text_changed = 0
        let g:ale_lint_on_insert_leave = 0
        let g:ale_lint_on_enter = 0
        let g:ale_lint_on_filetype_changed = 0

        " XXX There must be a better way than this to inherit a highlight group
        "     while changing an aspect of it.
        call hlset([hlget('LineNr', v:true)[0]->extend(#{name: 'ALEErrorSign', guifg: string(hlget('Error')[0].guibg)})])
        call hlset([hlget('LineNr', v:true)[0]->extend(#{name: 'ALEWarningSign', guifg: string(hlget('Todo')[0].guifg)})])
        call hlset([hlget('LineNr', v:true)[0]->extend(#{name: 'ALEInfoSign', guifg: string(hlget('Function')[0].guifg)})])

        let g:ale_sign_error = '▐'
        let g:ale_sign_style_error = '▐'
        let g:ale_sign_warning = '▐'
        let g:ale_sign_style_warning = '▐'
        let g:ale_sign_info = '▐'
    endif
endfunc

au VimEnter * call SetPluginSettings()
