" ~/.vimrc

execute pathogen#infect()

" Settings
set cc=80
set number
set hidden
set backup
set showcmd
set undofile
set wildmenu
set linebreak
set nocompatible
set backspace=indent,eol,start

syntax on
filetype indent plugin on

" 4 spaced expanded tabs by default
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

if &t_Co > 255 || has ('gui_running')
    colorscheme zenburn
endif

set guioptions=acM
set guifont=CMU\ Typewriter\ Text\ 11

set incsearch
set smartcase
set ignorecase

set cursorline
set laststatus=2
set statusline=%n.\ %F\ %M%=%y%w%r%h\ %{&fenc}\ (%l,%c)\ %p%%

" Speed up ESC in msec
set ttimeoutlen=50

" Use the Xorg’s secondary buffer as default register
set clipboard=unnamed

" Set directories
set undodir=~/.cache/vim/undo
set directory=~/.cache/vim/swap
set backupdir=~/.cache/vim/backup
set viminfo+=n~/.cache/vim/viminfo

" Fancy arrows are not welcome
let g:no_rust_conceal = 1

" Use clang when checking C syntax
let g:syntastic_c_compiler = 'clang'
