" ~/.vimrc

execute pathogen#infect()

set cc=80
set number
set hidden
set showcmd
set backspace=2
set nocompatible

if &t_Co > 255
    colorscheme zenburn
endif

set incsearch
set ignorecase
set smartcase

set laststatus=2
set statusline=%n.\ %f\ %M%=%y%w%r%h\ %{&fenc}\ (%l,%c)\ %p%%

" 4 spaced expanded tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Speed up ESC
set ttimeoutlen=50

" Use the X server's secondary buffer
set clipboard=unnamed

syntax on
filetype indent plugin on

" Move viminfo out of ~
set viminfo+=n~/.vim/viminfo

" Fancy arrows are not welcome
let g:no_rust_conceal = 1

" Use clang when checking C syntax
let g:syntastic_c_compiler = 'clang'
