#!/bin/sh --
# n2i - convert twitch user names to channel ids

# requires jq curl xargs sed

# POSIX sh with local
# shellcheck disable=SC2039

# Feel free to use these API keys.
# Backup: jzkbprff40iqj646a697cyrvl0zt2m6 (youtube-dl)
readonly client_id=rfbp97unyyikyzw1y9cy87iii29lgjk
readonly client_version=application/vnd.twitchtv.v5+json

chunkurls() {
    # Twitch only allows up to 100 logins to be specified per request.
    xargs -n 100 | sed 's!^!https://api.twitch.tv/kraken/users?login=!; s/ /,/g'
}

pulljson() {
    local url

    while read -r url; do
        if [ "$url" ]; then
            curl -sH "Accept: $client_version" -H "Client-ID: $client_id" "$url" | readjson &
        fi
    done

    wait
}

readjson() {
    jq -r '.users[] | ._id'
}

chunkurls | pulljson
