#!/bin/sh --
# t2s - generate streamer ids from a twitch team

# requires jq curl

# POSIX sh with local
# shellcheck disable=SC2039

# Feel free to use these API keys.
# Backup: jzkbprff40iqj646a697cyrvl0zt2m6 (youtube-dl)
readonly client_id=rfbp97unyyikyzw1y9cy87iii29lgjk
readonly client_version=application/vnd.twitchtv.v5+json

# NOTE: This leaves the responsibility of multi-tasking potentially many
#       processes to the kernel.  Neither gnu parallel(1) or xargs(1) proved
#       to be very capable of this without complication and awkwardness, and
#       neither were any faster.
pulljson() {
    local team

    while read -r team; do
        if [ "$team" ]; then
            curl -sH "Accept: $client_version" -H "Client-ID: $client_id"  https://api.twitch.tv/kraken/teams/"$team" | readjson &
        fi
    done

    wait
}

readjson() {
    jq -r '.users[] | ._id'
}

pulljson
