#!/bin/bash

# if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
#     eval "$(dbus-launch --sh-syntax --exit-with-session)"
# fi

# A better unclutter.
hhpc -i 3 &

# Wallpaper.
#display -window root -resize '1366x768!' ~/.local/share/wall &
xsetroot -mod 16 16 -fg '#343d46' -bg '#2b303b'

emacs --daemon &
dunst &

exec i3
