#!/bin/bash
# cleanup - utility to clear out playlist files with no matching menu entry

dir=${XDG_DATA_HOME:-$HOME/.local/share}/plaid/playlists

in_array() {
	local mark=$1
	local element

	for element in "${@:2}"; do
		if [[ $element == "$mark" ]]; then
            return 0
        fi
	done

    # Mark not found.
	return 1
}

[[ -s plaid_menu ]] || exit

while IFS='=' read -r k v; do
    if ! [[ $k =~ ^Title|^Command ]]; then
        playlists+=("$v")
    fi
done < plaid_menu


files=("$dir"/*)

for i in "${files[@]}"; do
    if ! in_array "$i" "${playlists[@]}"; then
        rm -vf -- "$i"
    fi
done
