# XDG_CONFIG_HOME/mpd/mpd.conf

# XXX mpd will not create these paths and returns an error if they do not
#     exist. The lack of idempotency complicates first starts.
music_directory "$HOME/music"
db_file "~/.local/share/mpd/mpd.db"
state_file "~/.local/var/lib/mpd/mpd.state"

bind_to_address "$XDG_RUNTIME_DIR/mpd"

restore_paused "no"
zeroconf_enabled "no"

audio_output {
    name "pipewire"
    type "pipewire"
}

# Silences warnings about lacking a timidity configuration file.
decoder {
    plugin "wildmidi"
    enabled "no"
}
