# XDG_CONFIG_HOME/mpd/mpd.conf

# XXX mpd will not create these paths and returns an error if they do not
#     exist. This complicates first starts.
music_directory "$HOME/music"
db_file "~/.local/share/mpd/mpd.db"
state_file "~/.local/var/lib/mpd/mpd.state"

bind_to_address "$XDG_RUNTIME_DIR/mpd"

restore_paused "no"
zeroconf_enabled "no"

audio_output {
    name "pulseaudio"
    type "pulse"
}

# Silences warnings about lacking a timidity configuration file.
decoder {
    plugin "wildmidi"
    enabled "no"
}

# XXX mpg123 is not robust against broken mp3 streams (cf. nightride.fm).
#     Using ffmpeg instead to prevent playlist skips with mpg123 errors.
#
#     [src/libmpg123/layer1.c:check_balloc():30] error: Illegal bit allocation value.
#     [src/libmpg123/layer1.c:INT123_do_layer1():228] error: Aborting layer I decoding after step one.
#     Note: Illegal Audio-MPEG-Header 0x3aa781cc at offset 988.
#     Note: Trying to resync...
#     Note: Skipped 32 bytes in input.
#     Warning: Big change from first (MPEG version, layer, rate). Frankenstein stream?
#     mpg123: mpg123_read() failed: Message: Prepare for a changed audio format (query the new one)!
#     mpg123: mpg123_read() failed: A generic mpg123 error.
decoder {
    plugin "mpg123"
    enabled "no"
}

decoder {
    plugin "ffmpeg"
    enabled "yes"
}
