#!/bin/sh --
# LOCALDIR/cfg/X11/xinitrc

# NOTE
#   This xinitrc should be POSIX sh as xinit starts it with /bin/sh.

# Give the localuser access to the Xserver using the Server Interpreted method
# (see Xsecurity(7)) which uses my user's UID via SO_PEERCRED to mediate access
# to the Xserver socket (/tmp/.X11-unix/X...).
xhost +si:localuser:"$USER"

xsetroot -mod 16 16 -fg '#343d46' -bg '#2b303b'
exec i3
