#!/bin/sh
# LOCALDIR/cfg/X11/xinitrc

# NOTE
#   This xinitrc should be POSIX sh as xinit starts it with /bin/sh.

# This is here primarily to prevent the creation of HOME/.dbus/session-bus/ by
# software using dbus.
if [ ! "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax)"
fi

# Give the localuser access to the Xserver using the Server Interpreted method
# (see Xsecurity(7)) which uses my user's UID via SO_PEERCRED to mediate access
# to the Xserver socket (/tmp/.X11-unix/X...).
xhost +si:localuser:"$USER"

xsetroot -mod 16 16 -fg '#343d46' -bg '#2b303b'
exec i3
