#!/bin/bash

# source_checked() {
#     local file=$1
#     [[ -f $file ]] && . "$file"
# }

# Import DISPLAY and XAUTHORITY into the systemd --user environment.
#source_checked /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

xsetroot -mod 16 16 -fg '#343d46' -bg '#2b303b'
exec i3
