# XDG_CONFIG_HOME/mpv/mpv.conf

title="MPV:${media-title:filename}"

hwdec=auto

# Provide useful visual feedback when for internet based streams as a window
# opening acts as a good indication something has occurred.
force-window=immediate

# https://github.com/mpv-player/mpv/issues/8418#issuecomment-2466772516
af=format=channels=stereo,dynaudnorm

volume=100
volume-max=400

sub-font="Inter"
osd-font="Inter"
osd-font-size=32

alang=en,eng
slang=en,eng

ytdl-raw-options=sub-lang="en,eng"

cache-pause-initial=yes

watch-later-options-append=pause

script-opts=osc-visibility_modes=always_auto

[doomscroll]
no-terminal
loop-file
loop-playlist
image-display-duration=inf
prefetch-playlist=yes

[cli]
terminal
video=no
force-window=no
audio-display=no
ytdl-format=bestaudio
term-title="${media-title}"

# Auto-profiles.
[sandybridge]
profile-cond=io.open('/proc/cpuinfo', 'r'):read('*all'):find('Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz')
profile=fast
vo=gpu
ytdl-format="(bv*[height <=? 1080][vcodec ~= '^(?:avc1|[hx]264)']+ba) / b"

[barcelo-r]
profile-cond=io.open('/proc/cpuinfo', 'r'):read('*all'):find('AMD Ryzen 5 PRO 7530U with Radeon Graphics')
vo=gpu-next
ytdl-format="(bv*[height <=? 1080][vcodec ~= '^(?:avc1|[hx]26[45]|vp9)']+ba) / b"

[twitch]
profile-cond=path:find('https://www.twitch.tv/')
mute=yes
terminal=no
gamma=10
ytdl-raw-options=live-from-start=
