#!/bin/sh --
# Get the name of the service from the PWD, this assumes the name of the
# service is one level above the log directory.
pwd=${PWD%/*}
service=${pwd##*/}

# mkdir -p "$HOME"/.local/var/log/"$service"
# exec svlogd -ttt "$HOME"/.local/var/log/"$service"
exec nice logger -et "$service" -p info
