#!/bin/sh --
# peon/uri - for anything that is not a local file
# requires curl mpv web peon trurl

if attr web; then
    case $1 in
    https://*|http://*)
        exec web "$1"
    ;;

    *)
        warn '%s: no matching web candidates\n' "$1"
    esac
fi

if attr video; then
    case $1 in
    https://www.twitch.tv/*|https://twitch.tv/*)
        exec mpv --mute=yes --terminal=no --gamma=10 --ytdl-raw-options=live-from-start= -- "$1"
    ;;

    *)
        exec mpv --profile=url -- "$1"
    esac
fi

case $1 in
file://*)
    # nb. Decodes a percent-encoded filepath and guards against trailing
    #     newline removal caused by process substitution.
    path=$(trurl -g {path}z -- "$1") path=${path%z}
    exec peon "${path#file://}"
;;

https://*.youtube.com/watch\?v=*|https://youtu.be/*)
    PEONATTRS=$(addattr video) exec peon "$1"
;;

https://www.youtube.com/shorts/*)
    PEONATTRS=$(addattr video) exec peon "$1"
;;

https://*.youtube.com/playlist?list=PL*)
    PEONATTRS=$(addattr video) exec peon "$1"
;;

https://www.twitch.tv/*)
    PEONATTRS=$(addattr video) exec peon "$1"
;;

https://*|http://*)
    case $1 in
    *.webm|*.mp4|*.m4a|*.mp3|*.gifv|*.opus)
        exec mpv --profile=url -- "$1"
    esac

    exec web "$1"
;;

ytdl://*)
    exec mpv -- "$1"
;;

*)
    web "g $1"
    warn '%s: no matching candidates\n' "$1"
esac
